from constants import R_bondi
default_dict={
    "input_folder":"/scratch/meemik/athenak/build_bondi_accr/src/adiaBondiAccrOut/bin",
    # "input_folder":"/home/meemik/athenak/build_cylindrical_jet/src/cylindrical_jet_10d/cylindricalJetAmbHalfOut/bin",
    "input_file": "bondi_accr.hydro_w.00001.bin",
    "loop_bin": True,
    "dt": 0.1,
    # "variable": "derived:velr",
    "variable": "dens",
    "cmap":"viridis",
    # "cmap_label":r"$P_{gas} (10^{-9}\, dyne\, cm^{-2})$ [log]",
    "cmap_label":r"$\rho (0.1 m_p cm^{-3})$ [log]",
    # "cmap_label":r"$T (K)$ [log]",
    # "cmap_label":r"$|v_r| [1000\, km/s]$",
    "norm":"log",
    # "norm":None,
    "direction": 'x3',
    "location":0,
    "extents": [None,None,None,None],
    # "clim": [0.0, 0.038],
    "clim": [None,None],
    "streamline_density": 5.0,
    "profile_variable":"x",
    "profile_slice":0,
    "figsize":(16,4),
    # "xlabel":"$x (kpc)$ [log]",
    "xlabel":"$x (kpc)$",
    "ylabel":"y (kpc)",
    # 'color':"green",
    'color':"blue",
    # 'color':"red",
    # 'color':"purple",
    "axes_scale":1.0
}