default_dict={
    "input_folder":"/scratch/meemik/athenak/build_bondi_accr/src/bondiAccrBigBoxOut/bin",
    # "input_folder":"/home/meemik/athenak/build_cylindrical_jet/src/cylindrical_jet_10d/cylindricalJetAmbHalfOut/bin",
    "input_file": "bondi_accr.hydro_w.00001.bin",
    "loop_bin": True,
    "dt": 0.1,
    "variable": "derived:velr",
    "cmap":"viridis",
    # "cmap_label":r"$P_{gas} [10^{-8} dyne cm^{-2}]$",
    # "cmap_label":r"$\rho [100 m_p cm^{-3}]$",
    # "cmap_label":r"$T [K]$",
    "cmap_label":r"$|v_r| [100 km/s]$",
    "norm":"log",
    "direction": 'x3',
    "location":0,
    "extents": [None,None,None,None],
    "clim": [0.0, 1.2],
    # "clim": [None,None],
    "streamline_density": 5.0,
    "profile_variable":"x",
    "profile_slice":0,
    "figsize":(16,4),
    "xlabel":"x (kpc)",
    "ylabel":"y (kpc)",
    'color':"purple",
    "axes_scale":0.1
}