from utils.constants import R_bondi


default_dict={
    "input_folder"              : "/scratch/meemik/athenak/build_wind_outflow_rad_bondi_uCGM/src/uCGMvw210kpcBox10MyrOut/bin",
    "tCGM_input_folder"         : "/scratch/meemik/athenak/build_wind_outflow_time_dependent_CGM/src/timeCGMrho01mpccVw1e2kmsMdot110kpcRadBondi10MyrOut/bin",
    "input_file"                : "wind_outflow_rad_bondi.hydro_w.00010.bin",
    "tCGM_input_file"           : "wind_outflow_rad_bondi.hydro_w.00010.bin",
    "loop_bin"                  : False,     
    # "loop_bin"                  : True,
    "dt"                        : 1.0,
    "time_label"                : "Myr",
    # "variable"                  : "velx",
    "variable"                  : "derived:velr",
    "profile_variable"          : "zh",
    "profile_slice"             : 0,
    # "variable"                  : "dens",
    # "cmap"                      : "Greens",
    "cmap_label"                :  r"v [km/s]",
    "norm"                      : None,
    # "clim"                      : [1.0e-4,1.0e-2],
    "clim"                      : [-10,1.0],
    "color"                     : "blue",
    "tCGM_color"                : "red",
    # "extents"                   : [None,None],
    # "variable"                  : [["dens","derived:pres"],["derived:temp","derived:tcool"]],
    # "cmap"                      : [["Greens","Blues"],["turbo", "red_purple_blue"]],
    # "cmap_label"                :  [[r"$\mathrm{n}\,(\mathrm{cm}^{-3})$",r"$\mathrm{P}\,(\mathrm{cgs})$"],[r"$\mathrm{T}\,(\mathrm{K})$",r"$\mathrm{t}_{\mathrm{cool}}\,(\mathrm{Myr})$"]],
    # "cmap_label"              :  r"$T (K)$ [log]",
    # "norm"                    : None,
    "direction"                 : 'x3',
    "location"                  : 0,
    # "norm"                      : [["log","log"],["log","log"]],
    # "extents"                   : [[None,None,None,None],[None,None,None,None]],
    # "clim"                      : [[1e-4, 1, 1e-15, 1e-11],[1e4,1e8,1e-3,1e3]],
    # "streamline_density"      : 5.0,
    # "profile_variable"          : "avg",
    # "profile_slice"             : 0,
    "figsize"                   : (13,4),
    # "xlabel"                  : "$x (kpc)$ [log]",
    "xlabel"                    : "x (kpc)",
    "ylabel"                    : "y (kpc)",
    # 'color'                   : "green",
    # 'color'                   : "blue",
    # 'color'                   : "red",
    # 'color'                   : "purple",
    # 'color'                   : "orange",
    # 'color'                     : "brown",
    "axes_scale"                : 1.0
}